### ISSUE TITLE
Give threads a name where possible

### ISSUE THREAD

**Issue by Xyene** [janestreet/magic-trace#146]
We currently name tracks as `pid/tid track_no`:

![image](https://user-images.githubusercontent.com/1403503/163290702-476cba4d-34e9-4cd0-a239-84e4d85095a8.png)

We can technically get thread names at `attach`/`run` time, and display them instead. There are cases where this definitely wouldn't work (thread gets started mid-trace) or might be wrong (thread exits, another thread gets started *with the same PID*), but I don't think these are important enough to be blockers: we can always fall back to showing the PID in the former case, or be wrong in the latter (I think we're wrong there anyway, should it happen).

**Comment by ahh** [comment]
> another thread gets started with the same PID

Linux makes (some) efforts to avoid this iirc, so seems unlikely. (In fact we could probably grab thread names _after trigger_ as well to pick up fresh threads?)

BTW, we should _always_ display TID (or at least make it findable on click somewhere?)  Many systems have not-very-good thread names since `comm` is a little-known feature (a particularly common thing I've seen is a small subset of a codebase knows about and sets it, but doesn't `unset` it, so threads look perpetually like they're associated with `foo` even if they're not.)

**Comment by cgaebel** [comment]
I agree that we should be careful to keep the TID around somewhere.

**Comment by Lamoreauxaj** [comment]
@Xyene Should this be closed?
